### PR TITLE
Ability to claim on-chain identity

### PR DESCRIPTION
**Pull request by singulart**
Implements https://github.com/Joystream/community-repo/issues/730 
Approved proposal: https://dao.joystream.org/#/proposals/preview/181

This PR introduces a lot of changes, so it may not be an easy job to review it. Important highlights: 
1. This repo is now a Nest.js app
2. Three modules are in place: Working Groups, Identity, Database
3. Database used under the hood to collect users' claimed identities (only public keys are stored!)
4. Two server commands are implemented `/claim` and `/solve`

### CODE REVIEW

**Comment by singulart** [comment]
@DzhideX please review this PR, thank you :)

**Comment by freakstatic** [comment]
LGTM!

**Comment by DzhideX** [comment]
Looks good on my end as well!

One question, I can't seem to find this `qntype` folder, am I missing something?

**Comment by singulart** [comment]
> Looks good on my end as well!
> 
> One question, I can't seem to find this `qntype` folder, am I missing something?

Good question! This file is auto-generated via `npm run generate` and therefore is added to `.gitignore`

**Pull request merged**
